version: "3"

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vectorjs-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    networks:
      - vectorjs-network

  mongodb:
    image: mongo:latest
    container_name: vectorjs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - vectorjs-mongodb:/data/db
    networks:
      - vectorjs-network

  mongodb-express:
    image: mongo-express
    container_name: vectorjs-mongodb-gui
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - vectorjs-network

networks:
  vectorjs-network:

volumes:
  vectorjs-mongodb:
